### ISSUE TITLE
base_classes feature not working

### ISSUE THREAD

**Issue by spaeps** [getgrav/grav-plugin-markdown-notices#11]
The *new* "base_classes" feature does not work in latest [release 1.0.2](https://github.com/getgrav/grav-plugin-markdown-notices/releases/tag/1.0.2), obviously, since [latest merged pull request](https://github.com/getgrav/grav-plugin-markdown-notices/pull/10) *"Allow adding inline notices, to use inside tables #10"* was wrongly written against [release 1.0.1](https://github.com/getgrav/grav-plugin-markdown-notices/releases/tag/1.0.1) and not against mainline, overwriting the [previous one](https://github.com/getgrav/grav-plugin-markdown-notices/pull/9) *"Ability to specify own base classes #9"*, thus deleting the entire feature implementation.

Please, revert #10 and rewrite the patch (or ask original submitter @miguelsalespereira) and push a new release.

Thank you

**Comment by rhukster** [comment]
Hmm.. usually Github does a good job of merging into develop, i'll try to fix this manually.

**Comment by rhukster** [comment]
Resolved and re-released.

**Comment by spaeps** [comment]
> Resolved and re-released.

Sorry but this is **not solved** at all.

The [patch applied](https://github.com/getgrav/grav-plugin-markdown-notices/commit/cce84239be37500cf547cb04fa56205cec95d387) is exactly the same as the [reverted pull request](https://github.com/getgrav/grav-plugin-markdown-notices/pull/10/files).

The patch has to be **rewritten** to **not** cut the *base_classes* parts or it would always **overwrite** them.

The only parts that should be merged are [from line 74 to line 110](https://github.com/getgrav/grav-plugin-markdown-notices/pull/10/files#diff-869a91a5a795c716917f30d3fb775b3cR74-R110) and [line 65](https://github.com/getgrav/grav-plugin-markdown-notices/pull/10/files#diff-869a91a5a795c716917f30d3fb775b3cR65) (see the links).

The **first set** is the one responsible for the **inline type** addition, but has to be patched more to include the *base_classes* detection or it would **not** work **inline** (but only in *block type*).

The **second set** removes the condition for the processed text starting with *"!"*, thus is unrelated and *probably* not necessary.

*IMHO*, since this feature is still **broken**, I suggest to *re-revert* the *re-applied* patch and *re-re-release* an **1.0.4** with only the *new* custom *base_classes* addition, that [was already applied in February](https://github.com/getgrav/grav-plugin-markdown-notices/pull/9) but **never** released (the reason I was using *git*).

Then, when the *inline* patch would be **ready** and **good**, it would be *re-re-applied* and *re-re-re-released* as **1.0.5**.

Thank you

**Comment by rhukster** [comment]
Ugg.. pain in the butt.  Please recreate the PR and i'll apply.  Cheers.
